#!/bin/bash

if type squidclient > /dev/null 2>&1 ; then
  echo "<<<check_squid>>>"

  # one squid instance
  squidclient -p 3128 -T2 mgr:5min | grep ' = '

  # multiple squid instances
  # instance names must be without spaces and with colon char at the end
  # squidclient -p 3128 -T2 mgr:5min | grep ' = ' | sed -e 's/^/Instance1:/'
  # squidclient -p 3129 -T2 mgr:5min | grep ' = ' | sed -e 's/^/Instance2:/'
fi
