#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Writed by Allan GooD: allan.cassaro@gmail.com
#

def inventory_ts(info):
    inventory = []
    if len(info) > 0 and len(info[0]) > 0:
        inventory.append(("Information",[]))
    return inventory

def check_ts(item, params, info):
    if (item == "Information"):
        name = info[0][0].strip()
        vendor = info[0][1].strip()
        id = info[0][2].strip()
        serial = info[0][3].strip()
    return (0, "Product name: %s - Vendor: %s - ID: %s - Serial: %s" % (name,vendor,id,serial))

check_info["check_ts3200_info"] = {
    'check_function':		check_ts,
    'inventory_function':	inventory_ts,
    'service_description':	'Tape Library TS3200 %s',
    'group':			'ts3200',
    'has_perfdata':		False,
}

snmp_info["check_ts3200_info"] = ( ".1.3.6.1.4.1.2.6.211", [ "1.1.0", "1.3.0", "3.1.1.8.1", "3.1.1.10.1" ] )
